import json

new_id = {
  "tag": "Katalog Produk",
  "h1": "Produk Kami",
  "p": "Temukan ribuan pilihan kemasan dan perlengkapan baking berkualitas untuk kebutuhan bisnis Anda — semua tersedia di satu tempat.",
  "tab_all": "Semua Produk",
  "cat1_label": "Kemasan Plastik", "cat2_label": "Kemasan Kertas",
  "cat3_label": "Kemasan Styrofoam", "cat4_label": "Peralatan Baking", "cat5_label": "Bahan Baking",
  "photo_soon": "Foto Segera",
  "p1_1_name": "Gelas Plastik & Tutup", "p1_1_desc": "Gelas bening food grade berbagai ukuran, cocok untuk minuman dingin & panas.",
  "p1_2_name": "Piring Plastik", "p1_2_desc": "Piring plastik food grade sekali pakai, ringan dan kuat untuk berbagai kebutuhan.",
  "p1_3_name": "Mika / Box Transparan", "p1_3_desc": "Kemasan mika transparan untuk display kue, snack, dan produk makanan lainnya.",
  "p1_4_name": "Botol Plastik", "p1_4_desc": "Botol plastik food grade berbagai ukuran untuk minuman, saus, dan produk cair.",
  "p1_5_name": "Kantong Plastik", "p1_5_desc": "Kantong plastik HD/LDPE berbagai ukuran dan ketebalan untuk packaging sehari-hari.",
  "p1_6_name": "Standing Pouch", "p1_6_desc": "Kemasan standing pouch dengan zipper, cocok untuk kopi, snack, dan produk kering.",
  "p1_7_name": "Thinwall", "p1_7_desc": "Wadah thinwall plastik ringan untuk nasi, lauk, dan makanan siap saji dengan tutup rapat.",
  "p1_8_name": "Toples Plastik", "p1_8_desc": "Toples plastik food grade berbagai ukuran untuk kue kering, camilan, dan bahan makanan.",
  "p2_1_name": "Gelas Kertas", "p2_1_desc": "Gelas kertas anti bocor berbagai ukuran untuk minuman panas maupun dingin.",
  "p2_2_name": "Box Makanan", "p2_2_desc": "Kotak makanan kraft food grade untuk nasi, ayam, dan berbagai menu siap saji.",
  "p2_3_name": "Mangkok Kertas", "p2_3_desc": "Mangkok kertas food grade untuk bubur, bakso, mie, dan makanan berkuah lainnya.",
  "p2_4_name": "Paper Bag", "p2_4_desc": "Paper bag kraft berbagai ukuran dan warna, cocok untuk branding toko dan produk.",
  "p2_5_name": "Kemasan Nasi", "p2_5_desc": "Kemasan kertas khusus nasi, tahan panas dan tidak bocor untuk katering dan restoran.",
  "p2_6_name": "Kemasan Kue & Snack", "p2_6_desc": "Box kue dan snack dari kertas food grade, berbagai ukuran untuk roti, brownies, dan tart.",
  "p2_7_name": "Kertas Roti", "p2_7_desc": "Kertas roti anti minyak (parchment paper) untuk alas dan pembungkus roti & kue.",
  "p3_1_name": "Box Styrofoam", "p3_1_desc": "Box styrofoam ringan dan tahan suhu untuk nasi, ayam goreng, dan aneka lauk pauk.",
  "p3_2_name": "Piring Styrofoam", "p3_2_desc": "Piring styrofoam sekali pakai ringan, cocok untuk acara, katering, dan warung makan.",
  "p3_3_name": "Mangkok Styrofoam", "p3_3_desc": "Mangkok styrofoam tahan panas untuk mie instan, bakso, soto, dan makanan berkuah.",
  "p3_4_name": "Ice Box Styrofoam", "p3_4_desc": "Ice box styrofoam tebal untuk menjaga suhu dingin ikan segar, daging, dan produk beku.",
  "p3_5_name": "Tray Buah", "p3_5_desc": "Tray styrofoam khusus untuk display dan packaging buah segar di toko dan pasar swalayan.",
  "p3_6_name": "Kemasan Daging & Sayur", "p3_6_desc": "Tray styrofoam untuk packaging daging segar, ayam potong, dan sayuran di supermarket.",
  "p4_1_name": "Pengocok Telur / Whisk", "p4_1_desc": "Pengocok telur stainless berbagai ukuran, ringan dan tahan lama untuk adonan kue.",
  "p4_2_name": "Timbangan Digital", "p4_2_desc": "Timbangan digital presisi untuk menimbang bahan kue dengan akurat hingga 0.1 gram.",
  "p4_3_name": "Cetakan Kue", "p4_3_desc": "Aneka cetakan kue dari aluminium dan silikon: bulat, kotak, karakter, dan berbagai bentuk.",
  "p4_4_name": "Spuit & Piping Bag", "p4_4_desc": "Set spuit dan piping bag untuk dekorasi kue, cupcake, dan roti dengan berbagai motif.",
  "p4_5_name": "Loyang Roti & Kue", "p4_5_desc": "Loyang anti lengket berbagai ukuran untuk memanggang roti, bolu, brownies, dan kue kering.",
  "p4_6_name": "Alas Adonan / Silpat", "p4_6_desc": "Alas adonan silikon anti lengket, mudah dibersihkan dan tahan panas.",
  "p4_7_name": "Botol Saus & Dispenser", "p4_7_desc": "Botol saus plastik food grade untuk penyimpanan dan aplikasi topping, saus, dan bahan cair.",
  "p5_1_name": "Tepung Terigu", "p5_1_desc": "Tepung terigu protein tinggi, sedang, dan rendah untuk berbagai jenis kue dan roti.",
  "p5_2_name": "Gula Pasir & Gula Halus", "p5_2_desc": "Gula pasir putih, gula halus, dan gula merah berkualitas untuk kebutuhan baking.",
  "p5_3_name": "Susu & Creamer", "p5_3_desc": "Susu bubuk, susu kental manis, dan creamer untuk berbagai resep kue dan minuman.",
  "p5_4_name": "Obat Kue / Baking Powder", "p5_4_desc": "Baking powder, soda kue, ragi instan, dan emulsifier untuk mengembangkan adonan.",
  "p5_5_name": "Coklat & Dark Chocolate", "p5_5_desc": "Coklat batang, coklat bubuk, dark chocolate, dan compound chocolate untuk dekorasi kue.",
  "p5_6_name": "Topping & Sprinkle", "p5_6_desc": "Aneka topping: meses, keju parut, sprinkle, almond slice, dan dekorasi kue lainnya.",
  "p5_7_name": "Pewarna & Essens", "p5_7_desc": "Pewarna makanan food grade dan berbagai essens rasa untuk tampilan dan aroma kue.",
}

new_en = {
  "tag": "Product Catalog",
  "h1": "Our Products",
  "p": "Discover thousands of quality packaging and baking supplies for your business needs — all available in one place.",
  "tab_all": "All Products",
  "cat1_label": "Plastic Packaging", "cat2_label": "Paper Packaging",
  "cat3_label": "Styrofoam Packaging", "cat4_label": "Baking Equipment", "cat5_label": "Baking Ingredients",
  "photo_soon": "Photo Coming Soon",
  "p1_1_name": "Plastic Cups & Lids", "p1_1_desc": "Food grade clear cups in various sizes, suitable for cold & hot beverages.",
  "p1_2_name": "Plastic Plates", "p1_2_desc": "Disposable food grade plastic plates, lightweight and sturdy for various needs.",
  "p1_3_name": "Acrylic / Clear Box", "p1_3_desc": "Transparent acrylic packaging for displaying cakes, snacks, and other food products.",
  "p1_4_name": "Plastic Bottles", "p1_4_desc": "Food grade plastic bottles in various sizes for beverages, sauces, and liquid products.",
  "p1_5_name": "Plastic Bags", "p1_5_desc": "HD/LDPE plastic bags in various sizes and thicknesses for everyday packaging needs.",
  "p1_6_name": "Standing Pouch", "p1_6_desc": "Standing pouch packaging with zipper, ideal for coffee, snacks, and dry products.",
  "p1_7_name": "Thinwall", "p1_7_desc": "Lightweight thinwall plastic containers for rice, side dishes, and ready-to-eat meals.",
  "p1_8_name": "Plastic Jars", "p1_8_desc": "Food grade plastic jars in various sizes for dry cakes, snacks, and food storage.",
  "p2_1_name": "Paper Cups", "p2_1_desc": "Leak-proof paper cups in various sizes for hot and cold beverages.",
  "p2_2_name": "Food Boxes", "p2_2_desc": "Kraft food grade food boxes for rice, chicken, and various ready-to-eat menus.",
  "p2_3_name": "Paper Bowls", "p2_3_desc": "Food grade paper bowls for porridge, meatballs, noodles, and other soupy foods.",
  "p2_4_name": "Paper Bags", "p2_4_desc": "Kraft paper bags in various sizes and colors, great for store and product branding.",
  "p2_5_name": "Rice Packaging", "p2_5_desc": "Special paper packaging for rice, heat-resistant and leak-proof for catering and restaurants.",
  "p2_6_name": "Cake & Snack Boxes", "p2_6_desc": "Food grade paper cake and snack boxes in various sizes for bread, brownies, and tarts.",
  "p2_7_name": "Bread Paper", "p2_7_desc": "Grease-proof parchment paper for lining and wrapping bread & cakes.",
  "p3_1_name": "Styrofoam Boxes", "p3_1_desc": "Lightweight and heat-resistant styrofoam boxes for rice, fried chicken, and side dishes.",
  "p3_2_name": "Styrofoam Plates", "p3_2_desc": "Lightweight disposable styrofoam plates, suitable for events, catering, and food stalls.",
  "p3_3_name": "Styrofoam Bowls", "p3_3_desc": "Heat-resistant styrofoam bowls for instant noodles, meatballs, and soupy dishes.",
  "p3_4_name": "Styrofoam Ice Boxes", "p3_4_desc": "Thick styrofoam ice boxes to keep fresh fish, meat, and frozen products cold.",
  "p3_5_name": "Fruit Trays", "p3_5_desc": "Styrofoam trays for displaying and packaging fresh fruit in stores and supermarkets.",
  "p3_6_name": "Meat & Vegetable Packaging", "p3_6_desc": "Styrofoam trays for packaging fresh meat, cut chicken, and vegetables in supermarkets.",
  "p4_1_name": "Egg Beater / Whisk", "p4_1_desc": "Stainless steel whisks in various sizes, lightweight and durable for mixing cake batter.",
  "p4_2_name": "Digital Scale", "p4_2_desc": "Precision digital scale for accurately weighing baking ingredients down to 0.1 grams.",
  "p4_3_name": "Cake Molds", "p4_3_desc": "Various cake molds in aluminum and silicone: round, square, character shapes, and more.",
  "p4_4_name": "Piping Tips & Bags", "p4_4_desc": "Piping tip and bag sets for decorating cakes, cupcakes, and bread with various patterns.",
  "p4_5_name": "Baking Pans", "p4_5_desc": "Non-stick baking pans in various sizes for baking bread, sponge cake, brownies, and cookies.",
  "p4_6_name": "Silicone Baking Mat", "p4_6_desc": "Non-stick silicone baking mat, easy to clean and heat-resistant.",
  "p4_7_name": "Sauce Bottles & Dispensers", "p4_7_desc": "Food grade plastic sauce bottles for storing and applying toppings, sauces, and liquids.",
  "p5_1_name": "Wheat Flour", "p5_1_desc": "High, medium, and low protein wheat flour for various types of cakes and bread.",
  "p5_2_name": "Granulated & Powdered Sugar", "p5_2_desc": "Quality granulated white sugar, powdered sugar, and brown sugar for baking.",
  "p5_3_name": "Milk & Creamer", "p5_3_desc": "Milk powder, condensed milk, and creamer for various cake and beverage recipes.",
  "p5_4_name": "Baking Agents", "p5_4_desc": "Baking powder, baking soda, instant yeast, and emulsifiers for leavening dough.",
  "p5_5_name": "Chocolate & Dark Chocolate", "p5_5_desc": "Chocolate bars, cocoa powder, dark chocolate, and compound chocolate for cake decoration.",
  "p5_6_name": "Toppings & Sprinkles", "p5_6_desc": "Various toppings: chocolate sprinkles, grated cheese, sprinkles, almond slices, and more.",
  "p5_7_name": "Food Coloring & Essence", "p5_7_desc": "Food grade coloring and various flavor essences for cake appearance and aroma.",
}

with open('lang/id.json','r',encoding='utf-8') as f: d = json.load(f)
d['products_page'] = new_id
with open('lang/id.json','w',encoding='utf-8') as f: json.dump(d,f,ensure_ascii=False,indent=2)
print("id.json updated")

with open('lang/en.json','r',encoding='utf-8') as f: d = json.load(f)
d['products_page'] = new_en
with open('lang/en.json','w',encoding='utf-8') as f: json.dump(d,f,ensure_ascii=False,indent=2)
print("en.json updated")
